[project]
name = "my_project"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
r = ">=4.4"
r-tidyverse = "*"
r-sf = "*"
r-terra = "*"
r-stars = "*"
r-tmap = "*"
r-mlr3 = "*"
r-pak = "*"

# TODO for pixi-r-py: pixi import ...